# Generated by Django 4.1.4 on 2022-12-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default_gallery.jpg', upload_to='gallery_pics'),
        ),
    ]
