# Generated by Django 4.1.4 on 2022-12-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='picture',
        ),
    ]
