# Generated by Django 4.1.4 on 2022-12-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_image_geo_location_image_peoples_names_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='geo_location',
        ),
        migrations.AddField(
            model_name='image',
            name='geo_location',
            field=models.ManyToManyField(blank=True, null=True, to='gallery.country'),
        ),
    ]
